CVAE:
  latent_dim: 64
  ref_filters: 32
  w_init: he_normal
  activation: leaky_relu
  dtype: float32
  seed: 42
  threshold: 0
  batch_sz: 2
  optimizer: adam
  learning_rate: 0.0003
  cost_function: MSE
  epochs: 500
  input_shape: [512, 512, 1] # [H, W, C] format

data:
  wkt:
    train_wkt: dataset/BurnedAreaUAV_dataset/WKT/train_valid.wkt
    test_wkt: dataset/BurnedAreaUAV_dataset/WKT/test.wkt
    unet_wkt: ~/unet.wkt
    sampled_masks_txt: data/sampled_masks.txt
    sampled_masks_wkt: data/sampled_masks.wkt
  full:
    train_dir: data/train
  sampled:
    train_dir: data/train_sampled
  unet:
    train_dir: data/unet_generated
  test:
    test_dir: data/test
  checkpoint_dir: checkpoints
  original_vid_dims: [1280, 720] # (W, H) format
  doi: 10.5281/zenodo.7944963D

outputs: 
  interpol:
    full: interpol/full
    sampled: interpol/sampled
  extrapol:
    full: extrapol/full
    sampled: extrapol/sampled

