
CVAE:
  latent_dim: 64
  ref_filters: 32
  w_init: he_normal
  activation: leaky_relu
  dtype: float32
  seed: 42
  threshold: 0.5
  batch_sz: 2
  optimizer: adam
  learning_rate: 0.0003
  cost_function: MSE
  epochs: 100



data:
  train_wkt: dataset/BurnedAreaUAV_dataset/WKT/train_valid.wkt
  test_wkt: dataset/BurnedAreaUAV_dataset/WKT/test.wkt
  train_dir: data/train
  test_dir: data/test
  train_sampled_dir: data/train_sampled
  sampled_masks_txt: data/sampled_masks.txt
  sampled_masks_wkt: data/sampled_masks.wkt
  original_vid_dims: [720, 1280]
  input_size: [512, 512, 1]      # [H, W, C] format
  doi: 10.5281/zenodo.7944963D
